/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Laboratorio-Info
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        btn_cadastrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Calculadora_btn = new javax.swing.JMenuItem();
        Notepad_btn = new javax.swing.JMenuItem();
        Navegador_btn = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Sair_btn = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Help_btn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jMenu1.setText("Cliente");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mail_send_mail_icon_264214 (1).png"))); // NOI18N
        jMenu6.setText("Relatorio");

        jMenuItem2.setText("Cliente");
        jMenu6.add(jMenuItem2);

        jMenuItem1.setText("Produto");
        jMenu6.add(jMenuItem1);

        jMenu1.add(jMenu6);

        btn_cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        btn_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mail_send_mail_icon_264214 (1).png"))); // NOI18N
        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(btn_cadastrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Produto");

        jMenuItem4.setText("jMenuItem4");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ferramentas");

        Calculadora_btn.setText("Calculadora");
        Calculadora_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora_btnActionPerformed(evt);
            }
        });
        jMenu3.add(Calculadora_btn);

        Notepad_btn.setText("Bloco de Notas");
        Notepad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Notepad_btnActionPerformed(evt);
            }
        });
        jMenu3.add(Notepad_btn);

        Navegador_btn.setText("Navegador");
        Navegador_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Navegador_btnActionPerformed(evt);
            }
        });
        jMenu3.add(Navegador_btn);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sair");

        Sair_btn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        Sair_btn.setText("Encerrar");
        Sair_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_btnActionPerformed(evt);
            }
        });
        jMenu4.add(Sair_btn);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        Help_btn.setText("Help");
        Help_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Help_btnActionPerformed(evt);
            }
        });
        jMenu5.add(Help_btn);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        JOptionPane.showMessageDialog(null, "Sem Funcionamento \n Volte mais tarde");
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void Sair_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_btnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Sair_btnActionPerformed

    private void Calculadora_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora_btnActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start calc.exe ") ;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ERRO P001\nCalculadora não encontrada");
        }
    }//GEN-LAST:event_Calculadora_btnActionPerformed

    private void Notepad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Notepad_btnActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start notepad.exe ") ;
        } catch (IOException ex) {
            Logger.getLogger(Menu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Notepad_btnActionPerformed

    private void Help_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Help_btnActionPerformed
       // C:\HELP.pdf
       try {
            Runtime.getRuntime().exec("cmd.exe /c C:\\HELP.pdf ") ;
        } catch (IOException ex) {
            Logger.getLogger(Menu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Help_btnActionPerformed

    private void Navegador_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Navegador_btnActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start chrome.exe www.google.com.br ") ;
        } catch (IOException ex) {
            Logger.getLogger(Menu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Navegador_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Calculadora_btn;
    private javax.swing.JMenuItem Help_btn;
    private javax.swing.JMenuItem Navegador_btn;
    private javax.swing.JMenuItem Notepad_btn;
    private javax.swing.JMenuItem Sair_btn;
    private javax.swing.JMenuItem btn_cadastrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
